08/03/2025 09:17:45 PM function setup_training_pipeline called with args 
08/03/2025 09:17:45 PM Device: cpu
08/03/2025 09:17:45 PM Batch size: 32
08/03/2025 09:17:45 PM Learning rate: 0.001
08/03/2025 09:17:45 PM Step 1: Creating data splits...
08/03/2025 09:18:12 PM Step 2: Creating data loaders...
08/03/2025 09:18:12 PM Exception raised in setup_training_pipeline. exception: AquaticLifeDataset() got an unexpected keyword argument 'data_dir'
Traceback (most recent call last):
  File "/Users/adonisserrano/Documents/GitHub/aquatic-life-classifier/src/utils/management/decorators.py", line 57, in wrapper
    res = func(*args, *kwargs)
  File "/Users/adonisserrano/Documents/GitHub/aquatic-life-classifier/src/data_pipeline/pipeline_service.py", line 161, in setup_training_pipeline
    train_loader, val_loader, test_loader, class_to_idx = create_data_loaders(
  File "/Users/adonisserrano/Documents/GitHub/aquatic-life-classifier/src/data_pipeline/utils/data_helpers.py", line 197, in create_data_loaders
    train_dataset = AquaticLifeDataset(
TypeError: AquaticLifeDataset() got an unexpected keyword argument 'data_dir'
