08/03/2025 09:57:37 PM function setup_training_pipeline called with args 
08/03/2025 09:57:37 PM Device: cpu
08/03/2025 09:57:37 PM Batch size: 32
08/03/2025 09:57:37 PM Learning rate: 0.001
08/03/2025 09:57:37 PM Step 1: Creating data splits...
08/03/2025 09:58:03 PM Step 2: Creating data loaders...
08/03/2025 09:58:03 PM Exception raised in setup_training_pipeline. exception: '<' not supported between instances of 'list' and 'int'
Traceback (most recent call last):
  File "/Users/adonisserrano/Documents/GitHub/aquatic-life-classifier/src/utils/management/decorators.py", line 57, in wrapper
    res = func(*args, *kwargs)
  File "/Users/adonisserrano/Documents/GitHub/aquatic-life-classifier/src/data_pipeline/pipeline_service.py", line 161, in setup_training_pipeline
    train_loader, val_loader, test_loader, class_to_idx = create_data_loaders(
  File "/Users/adonisserrano/Documents/GitHub/aquatic-life-classifier/src/data_pipeline/utils/data_helpers.py", line 199, in create_data_loaders
    train_dataset = AquaticLifeDataset(
  File "/Users/adonisserrano/Documents/GitHub/aquatic-life-classifier/src/data_pipeline/utils/data_helpers.py", line 38, in __init__
    self._load_dataset()
  File "/Users/adonisserrano/Documents/GitHub/aquatic-life-classifier/src/data_pipeline/utils/data_helpers.py", line 44, in _load_dataset
    n, labels = sorted(get_labels(self.data_dir))
TypeError: '<' not supported between instances of 'list' and 'int'
